version: '3.8'
services:
  waysgallery-frontend:
     container_name: waysgallery-frontend
     image: dhanifajar15/waysgallery-frontend
     stdin_open: true
     ports:
       - 3000:3000
     environment: 
       - NODE_ENV=production
